// --------------------------------------------------------------------------------------------------------------------
// <copyright>
// Copyright © 2012 - 2014 Strategic Forge
//
// Email: jim@strategicforge.com
// </copyright> 
// <summary> 
// File: FacilityStat.cs
// Immutable struct containing externally acquirable values for Facilities.
// </summary> 
// -------------------------------------------------------------------------------------------------------------------- 

#define DEBUG_LOG
#define DEBUG_WARN
#define DEBUG_ERROR

namespace CodeEnv.Master.GameContent {

    using CodeEnv.Master.Common;

    /// <summary>
    /// Immutable struct containing externally acquirable values for Facilities.
    /// </summary>
    public struct FacilityStat {

        public string Name { get; private set; }
        public float Mass { get; private set; }
        public float MaxHitPoints { get; private set; }
        public FacilityCategory Category { get; private set; }
        public float Science { get; private set; }
        public float Culture { get; private set; }
        public float Income { get; private set; }
        public float Expense { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="FacilityStat" /> struct.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="mass">The mass.</param>
        /// <param name="maxHitPts">The maximum hit PTS.</param>
        /// <param name="category">The category.</param>
        /// <param name="science">The science.</param>
        /// <param name="culture">The culture.</param>
        /// <param name="income">The income generated by this facility.</param>
        /// <param name="expense">The expense consumed by this facility.</param>
        public FacilityStat(string name, float mass, float maxHitPts, FacilityCategory category, float science, float culture,
            float income, float expense)
            : this() {
            Name = name;
            Mass = mass;
            MaxHitPoints = maxHitPts;
            Category = category;
            Science = science;
            Culture = culture;
            Income = income;
            Expense = expense;
        }

        public override string ToString() {
            return new ObjectAnalyzer().ToString(this);
        }

    }
}

