// --------------------------------------------------------------------------------------------------------------------
// <copyright>
// Copyright © 2012 - 2013 Strategic Forge
//
// Email: jim@strategicforge.com
// </copyright> 
// <summary> 
// File: GuiManager.cs
// Overall GuiManager that handles the visibility of Gui elements.
// </summary> 
// -------------------------------------------------------------------------------------------------------------------- 

#define DEBUG_LOG
#define DEBUG_WARN
#define DEBUG_ERROR

// default namespace

using System;
using System.Collections.Generic;
using System.Linq;
using CodeEnv.Master.Common;
using CodeEnv.Master.Common.LocalResources;
using CodeEnv.Master.GameContent;
using UnityEngine;

/// <summary>
/// Overall GuiManager that handles the visibility of Gui elements.
/// </summary>
public class GuiManager : AMonoBaseSingleton<GuiManager>, IDisposable {

    public bool ReadyForSceneChange { get; private set; }

    private Stack<IList<UIPanel>> _stackedPanelsToReappear;
    private UIPanel[] _panelsThatNeverDisappear;
    private GameEventManager _eventMgr;

    protected override void Awake() {
        base.Awake();
        _stackedPanelsToReappear = new Stack<IList<UIPanel>>();
        _eventMgr = GameEventManager.Instance;
        UIPanel uiRootPanel = gameObject.GetSafeMonoBehaviourComponent<UIRoot>().gameObject.GetSafeMonoBehaviourComponent<UIPanel>();
        UIPanel tooltipPanel = gameObject.GetSafeMonoBehaviourComponentInChildren<UITooltip>().gameObject.GetSafeMonoBehaviourComponent<UIPanel>();
        _panelsThatNeverDisappear = new UIPanel[] { uiRootPanel, tooltipPanel };
        Subscribe();
    }

    protected override void Start() {
        base.Start();
        CheckDebugSettings();
    }

    //[System.Diagnostics.Conditional("UNITY_EDITOR")]
    private void CheckDebugSettings() {
        DebugSettings debugSettings = DebugSettings.Instance;
        if (debugSettings.DisableGui) {
            Camera guiCamera = gameObject.GetSafeMonoBehaviourComponentInChildren<UICamera>().camera;
            guiCamera.enabled = false;
        }
        if (!debugSettings.EnableFpsReadout) {
            GameObject fpsReadoutParentGo = gameObject.GetSafeMonoBehaviourComponentInChildren<FpsReadout>().transform.parent.gameObject;
            fpsReadoutParentGo.SetActive(false);
        }
    }

    private void Subscribe() {
        _eventMgr.AddListener<GuiVisibilityButton.GuiVisibilityChangeEvent>(Instance, OnGuiVisibilityChange);
        _eventMgr.AddListener<BuildNewGameEvent>(Instance, OnBuildNewGame);
        _eventMgr.AddListener<LoadSavedGameEvent>(Instance, OnLoadSavedGame);
    }

    private void OnLoadSavedGame(LoadSavedGameEvent e) {
        MakeAllPanelsReappear();
    }

    private void OnBuildNewGame(BuildNewGameEvent e) {
        MakeAllPanelsReappear();
    }

    /// <summary>
    /// Restores all panels to visibility in preparation for a scene change.
    /// </summary>
    private void MakeAllPanelsReappear() {
        //D.Log("Restoring all panels to visibility in preparation for scene change.");
        for (int i = 0; i < _stackedPanelsToReappear.Count; i++) {
            var panelsToReappear = _stackedPanelsToReappear.Pop();
            ChangeVisibility(true, panelsToReappear);
        }
        ReadyForSceneChange = true;
        // no need to reset this to false after as GuiManagers donot survive scene changes
    }

    private void OnGuiVisibilityChange(GuiVisibilityButton.GuiVisibilityChangeEvent e) {
        if (ReadyForSceneChange) {
            // if we are ready for a scene change, all panels have already been restored and this event generated by the button is superfluous
            return;
        }
        //D.Log("OnGuiVisibilityChange event received. GuiVisibilityCmd = {0}.", e.GuiVisibilityCmd);
        switch (e.GuiVisibilityCmd) {
            case GuiVisibilityCommand.HideVisibleGuiPanels:
                var activeUIRootChildPanelCandidates = gameObject.GetSafeMonoBehaviourComponentsInChildren<UIPanel>().Except(_panelsThatNeverDisappear);
                // Can't use UIPanel.list as it contains ALL active UIPanels, not just those in the 2DUI
                // D.Log("Active 2DUI UIPanels found on HideVisibleGuiPanels event: \n{0}.", activeUIRootChildPanelCandidates.Concatenate());
                var panelsToDisappear = activeUIRootChildPanelCandidates.Except(e.Exceptions);
                ChangeVisibility(false, panelsToDisappear);
                _stackedPanelsToReappear.Push(panelsToDisappear.ToList<UIPanel>());
                break;
            case GuiVisibilityCommand.RestoreInvisibleGuiPanels:
                D.Assert(_stackedPanelsToReappear.Count != Constants.Zero, "The stack holding the lists of UIPanels to restore should not be empty!");
                var panelsToReappear = _stackedPanelsToReappear.Pop().Except(e.Exceptions);
                ChangeVisibility(true, panelsToReappear);
                break;
            case GuiVisibilityCommand.None:
            default:
                throw new NotImplementedException(ErrorMessages.UnanticipatedSwitchValue.Inject(e.GuiVisibilityCmd));
        }
    }

    private void ChangeVisibility(bool isVisible, IEnumerable<UIPanel> panels) {
        //string visibility = isVisible ? "now visible" : "no longer visible";
        panels.ForAll(p => {
            NGUITools.SetActive(p.gameObject, isVisible);
            // There is an alternative way using the Panel's alpha property to manage the panel's widget's visibility. 
            // The issue I encountered was the current algorithm finds ALL panels, not just those onscreen, and
            // makes them invisible (deactivates them). While MyNguiPlayAnimation.ifDisabledOnPlay = enableThenPlay;
            // reactivates any UIPanels it intends to play, there is no such setting to fix the UIPanel if its alpha = 0.
            //var uiWindow = p.gameObject.GetComponent<UIWindow>();   // assumes max of 1 UIWindow per panel
            //if (uiWindow != null) {
            //    if (isVisible) {
            //        uiWindow.Show();
            //    }
            //    else {
            //        uiWindow.Hide();
            //    }
            //}
            //else {
            //    p.alpha = isVisible ? 1.0F : Constants.ZeroF;
            //}
            //D.Log("UIPanel {0} is {1}.", p.gameObject.name, visibility);
        });
    }

    protected override void OnDestroy() {
        base.OnDestroy();
        Dispose();
    }

    private void Cleanup() {
        Unsubscribe();
    }

    private void Unsubscribe() {
        _eventMgr.RemoveListener<GuiVisibilityButton.GuiVisibilityChangeEvent>(Instance, OnGuiVisibilityChange);
        _eventMgr.RemoveListener<BuildNewGameEvent>(Instance, OnBuildNewGame);
        _eventMgr.RemoveListener<LoadSavedGameEvent>(Instance, OnLoadSavedGame);
    }

    public override string ToString() {
        return new ObjectAnalyzer().ToString(this);
    }

    #region IDisposable
    [NonSerialized]
    private bool alreadyDisposed = false;

    /// <summary>
    /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
    /// </summary>
    public void Dispose() {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// Releases unmanaged and - optionally - managed resources. Derived classes that need to perform additional resource cleanup
    /// should override this Dispose(isDisposing) method, using its own alreadyDisposed flag to do it before calling base.Dispose(isDisposing).
    /// </summary>
    /// <arg name="isDisposing"><c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</arg>
    protected virtual void Dispose(bool isDisposing) {
        // Allows Dispose(isDisposing) to be called more than once
        if (alreadyDisposed) {
            return;
        }

        if (isDisposing) {
            // free managed resources here including unhooking events
            Cleanup();
        }
        // free unmanaged resources here
        alreadyDisposed = true;
    }


    // Example method showing check for whether the object has been disposed
    //public void ExampleMethod() {
    //    // throw Exception if called on object that is already disposed
    //    if(alreadyDisposed) {
    //        throw new ObjectDisposedException(ErrorMessages.ObjectDisposed);
    //    }

    //    // method content here
    //}
    #endregion

}

