// --------------------------------------------------------------------------------------------------------------------
// <copyright>
// Copyright © 2012 - 2014 Strategic Forge
//
// Email: jim@strategicforge.com
// </copyright> 
// <summary> 
// File: ResponsiveTrackingSprite.cs
// Sprite resident in world space that can respond to the mouse. 
// </summary> 
// -------------------------------------------------------------------------------------------------------------------- 

#define DEBUG_LOG
#define DEBUG_WARN
#define DEBUG_ERROR

// default namespace

using CodeEnv.Master.Common;
using CodeEnv.Master.GameContent;
using UnityEngine;

/// <summary>
/// Sprite resident in world space that can respond to the mouse. 
/// The user perceives the widget at a constant size, independent of camera distance.
/// </summary>
public class ResponsiveTrackingSprite : ConstantSizeTrackingSprite, IResponsiveTrackingSprite {

    public ICameraLosChangedListener CameraLosChangedListener { get; private set; }

    public IMyEventListener EventListener { get; private set; }

    private IconInfo _iconInfo;
    public IconInfo IconInfo {
        get { return _iconInfo; }
        set { SetProperty<IconInfo>(ref _iconInfo, value, "IconInfo", IconInfoPropChangedHandler); }
    }

    private Collider _collider;

    protected override void Awake() {
        base.Awake();
        GameObject widgetGo = WidgetTransform.gameObject;
        NGUITools.AddWidgetCollider(widgetGo);
        _collider = widgetGo.GetSafeComponent<Collider>();
        _collider.isTrigger = true;
        _collider.enabled = false;
        CameraLosChangedListener = widgetGo.AddComponent<CameraLosChangedListener>();
        EventListener = widgetGo.AddComponent<MyEventListener>();
    }

    public override void __SetDimensions(int width, int height) {
        base.__SetDimensions(width, height);
        NGUITools.UpdateWidgetCollider(WidgetTransform.gameObject);
    }

    protected override void Show() {
        base.Show();
        _collider.enabled = true;
    }

    protected override void Hide() {
        base.Hide();
        _collider.enabled = false;
        // Note: donot disable CameraLosChangedListener, as disabling it will also eliminate OnBecameVisible() events
    }

    #region Event and Property Change Handlers

    private void IconInfoPropChangedHandler() {
        AtlasID = IconInfo.AtlasID;
        Set(IconInfo.Filename);
        Color = IconInfo.Color;
    }

    protected override void AlignWidgetOtherTo(WidgetPlacement placement) {
        base.AlignWidgetOtherTo(placement);
        // reposition the collider to account for the widget's pivot generated by the placement value
        NGUITools.UpdateWidgetCollider(WidgetTransform.gameObject);
    }

    #endregion

    public override string ToString() {
        return new ObjectAnalyzer().ToString(this);
    }

}

